### ISSUE TITLE
Implement JSON-formatted output

### ISSUE THREAD

**Issue by kaimallea** [kaimallea/demoinfogo-linux#7]
It'd be nice if the output could be easily ingested. The current output format is lame and requires parsing.

Example of current output:

```
---- CSVCMsg_TempEntities (11 bytes) -----------------
num_entries: 1
entity_data: "\302\236\377\337\000\330\265"
player_death eventid:23
 userid: 33
 attacker: 33
 assister: 0
 weapon: world
 weapon_itemid:
 weapon_fauxitemid:
 weapon_originalowner_xuid:
 headshot: 0
 dominated: 0
 revenge: 0
 penetrated: 0
```
